apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: database
            - name: DB_NAME
              value: messageboard
            - name: DB_PASSWORD
              value: messageboard
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
          image: api
          name: api-container
          ports:
            - containerPort: 4001
              protocol: TCP
            - containerPort: 4000
              protocol: TCP
      restartPolicy: Always
