kind: Deployment
apiVersion: apps/v1
metadata:
  name: messageboard-deployment
spec:
  selector:
    matchLabels:
      app: flask-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-pod
    spec:
      containers:
        - name: ms1
          image: nihu21/ms1:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 9001
        - name: frontend
          image: nihu21/frontend:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 5001
        - name: ms2
          image: nihu21/ms2:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 9002
        - name: api
          image: nihu21/api:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 4001
      
      