apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: microservice1
  name: microservice1
spec:
  ports:
    - name: "1313"
      port: 1313
      targetPort: 9001
    - name: 1313-tcp
      port: 1313
      targetPort: 1313
  selector:
    io.kompose.service: microservice1
